<a href="https://colab.research.google.com/github/BrayFlo/Mineria-Datos/blob/main/TeoremaBayesEjer2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#17 de Marzo del 2026
#Bryan Hernandez Flores

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import numpy as np

In [2]:
data = {
    'titular': [
    "equipo gana campeonato",
    "nuevo telefono inteligente",
    "jugador anota gol decisivo",
    "empresa lanza nueva computadora",
    "equipo gana torneo"
    ],

    'clase': [
        "deportes",
        "tecnologia",
        "deportes",
        "tecnologia",
        "deportes"
    ]
}

df = pd.DataFrame(data)
print(df)

                           titular       clase
0           equipo gana campeonato    deportes
1       nuevo telefono inteligente  tecnologia
2       jugador anota gol decisivo    deportes
3  empresa lanza nueva computadora  tecnologia
4               equipo gana torneo    deportes


In [3]:
#Convertir el texto en una matriz de caracteristicas
vectorizador = CountVectorizer()
X = vectorizador.fit_transform(df['titular'])
print(X.toarray())

[[0 1 0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 1 0]
 [1 0 0 1 0 0 0 1 0 1 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 1]]


In [4]:
#Establever la variable objetivo
y = df['clase']

#Entrenar el modelo de Naive Bayes
modelo = MultinomialNB()
modelo.fit(X, y)

#Predecir la clase de un nuevo correo
nuevo_correo = ["equipo gana torneo"]
correo_vectorizado = vectorizador.transform(nuevo_correo)
prediccion = modelo.predict(correo_vectorizado)
print(prediccion)

['deportes']
